apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      hostname: broker
      containers:
      - env:
        - name: borker
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: <ZOOKEEPER-INTERNAL-IP>:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:29092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker:29092
        image: confluentinc/cp-zookeeper:7.0.1
        imagePullPolicy: IfNotPresent
        name: broker
        ports:
        - containerPort: 29092