global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'customer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer:8089']
        labels:
          application: 'Customer Service Application'
  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification:8081']
        labels:
          application: 'Notification Service Application'